AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create an SFTP service using AWS Transfer for SFTP.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID of the VPC where you want to deploy the SFTP service.

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: ID of the subnet where you want to deploy the SFTP service.

Resources:
  SftpServer:
    Type: AWS::Transfer::Server
    Properties:
      IdentityProviderType: SERVICE_MANAGED
      EndpointType: VPC
      SecurityPolicyName: TransferSecurityPolicy
      Tags:
        - Key: Name
          Value: SFTP-Server

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the SFTP server
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: SFTP-SecurityGroup

  InboundRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref SecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      SourceSecurityGroupId: !Ref SecurityGroup

  SubnetAssociation:
    Type: AWS::Transfer::Server::User
    Properties:
      ServerId: !Ref SftpServer
      UserName: sftp-user
      HomeDirectory: /
      HomeDirectoryType: LOGICAL
      Role: "arn:aws:iam::aws:policy/service-role/Transfer_DefaultRole"
      Policy: "arn:aws:iam::aws:policy/service-role/Transfer_DefaultPolicy"
      Tags:
        - Key: Name
          Value: sftp-user

Outputs:
  SftpServerId:
    Description: ID of the created SFTP server.
    Value: !Ref SftpServer

  SftpServerEndpoint:
    Description: Endpoint of the created SFTP server.
    Value: !GetAtt SftpServer.Endpoint
