AWSTemplateFormatVersion: '2010-09-09'
Description: Create an AWS Transfer Family SFTP server with internal endpoint option

Parameters:
  SecurityGroupId:
    Type: String
    Description: ID of the security group for the SFTP server
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket for storing files

Resources:
  SFTPServer:
    Type: AWS::Transfer::Server
    Properties:
      EndpointType: VPC
      EndpointDetails:
        VpcEndpointId: "vpce-1234567890abcdef0" # Replace with your VPC endpoint ID
      IdentityProviderType: SERVICE_MANAGED
      LoggingRole: ""
      SecurityGroups:
        - !Ref SecurityGroupId

  SFTPUser:
    Type: AWS::Transfer::User
    Properties:
      ServerId: !Ref SFTPServer
      UserName: testuser
      HomeDirectory: "/"
      Role: ""
      Policy: ""
      SshPublicKeyBody: ""

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: transfer.amazonaws.com
            Action: s3:GetBucketLocation
            Resource: !Sub arn:aws:s3:::${S3BucketName}
          - Effect: Allow
            Principal:
              Service: transfer.amazonaws.com
            Action: s3:ListBucket
            Resource: !Sub arn:aws:s3:::${S3BucketName}
          - Effect: Allow
            Principal:
              Service: transfer.amazonaws.com
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: !Sub arn:aws:s3:::${S3BucketName}/*
